export const SliderData = [
     {
          type: 'men',
          brand: "Levis",
          category: "t-shirts",
          defaultImage:
               "https://m.media-amazon.com/images/I/71FL4bSMydL._UL1500_.jpg",
          description: "Men T-Shirt",
          discount: 20,
          id: "4SkCLBVHYcqpJMsM8qDK",
          images: {
               image3: "",
               image2: "",
               image1: "https://m.media-amazon.com/images/I/71UmoGD3U6L._UL1500_.jpg",
          },
          mrp: 899,
          price: 799,
          rating: 3,
          totalReview: "34k",
     },
     {
          type: 'women',
          brand: "RSVP by Nykaa Fashion",
          category: "Tops ",
          defaultImage:
               "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/c/1/tr:w-960,/c1d8393T20082_1.jpg?rnd=20200526195200",
          description: "Blue Stroke Of Elegance Camisole",
          discount: 15,
          id: "40dx3Wo4tMR45Q1BzXMF",
          images: {
               image3: "",
               image1: "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/2/a/2aff338DFS1191B_1.jpg",
               image2: "https://adn-static1.nykaa.com/nykdesignstudio-imag…/tr:w-960,/c1d8393T20082_2.jpg?rnd=20200526195200",
          },
          mrp: 2295,
          price: 1951,
          rating: 3.4,
          totalReview: "23k",
     },
     {
          type: 'kids',
          brand: "Pink Chick",
          category: "Frock",
          defaultImage:
               "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/5/c/tr:w-960,/5cf5b19PCF25_3.jpg",
          description: "Layers Party Dress -navy Multi",
          discount: 50,
          id: "jrI2Y7TdLKTleHQxRp3n	",
          images: {
               image3: "",
               image2: "",
               image1: "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/5/c/tr:w-960,/5cf5b19PCF25_2.jpg",
          },
          mrp: 1700,
          price: 3000,
          rating: 4,
          totalReview: "56k",
     },
     {
          type: 'women',
          brand: "Lea Clothing",
          category: "Jeans",
          defaultImage:
               "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/f/7/tr:w-960,/f7a6c12NYKFF_LEAC0072_1.jpg?rnd=20200526195200",
          description: "Blue Ava Wide Leg Jeans",
          discount: 1,
          id: "yrkWAwjbNqWFZbfC4j3a",
          images: {
               image2: "https://adn-static1.nykaa.com/nykdesignstudio-imag…0,/f7a6c12NYKFF_LEAC0072_2.jpg?rnd=20200526195200",
               image3: "",
               image1: "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/i/n/indi-inside-leh104-ylw_fs_1_1916c911.jpg",
          },
          mrp: 2990,
          price: 2980,
          rating: 4.5,
          totalReview: "55k",
     },
     {
          type: 'men',
          brand: "Roadster",
          category: "t-shirts",
          defaultImage:
               "https://m.media-amazon.com/images/I/71tJWaahoDL._UL1500_.jpg",
          description: "Men Grey Melange Longline T-shirt with Raw Edges",
          discount: 55,
          id: "LUGjt7OhFaXSCYHCLsOt",
          images: {
               image3: "",
               image2: "",
               image1: "https://m.media-amazon.com/images/I/71tlQII1TXL._UL1500_.jpg",
          },
          mrp: 799,
          price: 359,
          rating: 4,
          totalReview: "56k",
     },
     {
          type: 'women',
          brand: "Aachho",
          category: "Kurtis",
          defaultImage:
               "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/a/8/tr:w-960,/a8cd93aACHNGJUL27_1.jpg?rnd=20200526195200",
          description: "Neria Gotapatti Tier Suit (Set of 3)",
          discount: 10,
          id: "Tl9uQRRVqODLV9AymQlQ",
          images: {
               image3: "",
               image2: "https://adn-static1.nykaa.com/nykdesignstudio-imag…-960,/a8cd93aACHNGJUL27_10.jpg?rnd=20200526195200",
               image1: "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/f/5/f5607dcNFTD_TWDR1018_1.jpg",
          },
          mrp: 5750,
          price: 5175,
          rating: 4.4,
          totalReview: "22k",
     },
    
     {
          type: 'women',
          brand: "Lavanya The Label",
          category: "Sarees",
          defaultImage:
               "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/c/b/tr:w-960,/cbce07bLBL101KS396_1.jpg?rnd=20200526195200",
          description:
               "Yellow Sequin Organza Ruffled Saree with Stitched Blouse",
          discount: 10,
          id: "j7yY5Qixf6dGGl44dmMY",
          images: {
               image3: "",
               image2: "https://adn-static1.nykaa.com/nykdesignstudio-imag…960,/cbce07bLBL101KS396_10.jpg?rnd=20200526195200",
               image1: "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/4/9/496fdd4N799_1.jpg",
          },
          mrp: 5699,
          price: 5130,
          rating: 3.4,
          totalReview: "23k",
     },
     {
          type: 'men',
          brand: "Roadster",
          category: "Shirts",
          defaultImage:
               "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/6/1/61ca84cD_FSAW16111PGRN_1.jpg",
          description: "Men Grey Melange Longline T-shirt with Raw Edges",
          discount: 50,
          id: "kAaa68LqfFPYgEz1dDNk",
          images: {
               image3: "",
               image2: "",
               image1: "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/5/0/502cf1fTBH-TONIC-RT_1.jpg",
          },
          mrp: 799,
          price: 359,
          rating: 4,
          totalReview: "56k",
     },
    
]

